# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_auto_20170410_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='deuce_count',
            new_name='player_one_deuce_count',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='status',
            new_name='player_one_status',
        ),
        migrations.AddField(
            model_name='match',
            name='player_two_deuce_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player_two_status',
            field=models.CharField(default='status', max_length=40),
        ),
    ]
